<a href="https://colab.research.google.com/github/bhanuprakash227/DataScience---Exelr/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import pandas as pd

In [67]:
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [68]:
s.dtype

dtype('int64')

In [69]:
s.values

array([10, 20, 30, 40, 50])

In [70]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [71]:
print(s.name)

None

In [72]:
s.name = "calories"

In [73]:
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

In [74]:
# Indexing

s[0]

np.int64(10)

In [75]:
s[0:2] #start(included) : stop (excluded): step value (values to jump)

0    10
1    20
Name: calories, dtype: int64

In [76]:
s[2:4]

2    30
3    40
Name: calories, dtype: int64

In [77]:
# iloc -> location based indexing

s.iloc[3]

np.int64(40)

In [78]:
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: calories, dtype: int64

In [79]:
index = ["apple", "banana", "grapes", "orange", "strawberry"]

In [80]:
s.index = index
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

In [81]:
s['grapes']

np.int64(30)

In [82]:
s.iloc[3]

np.int64(40)

In [83]:
#loc -> label based indexing.
s.loc[['grapes', 'apple']]

grapes    30
apple     10
Name: calories, dtype: int64

In [84]:
# In label based indexing your start as well as stop value both are included in the output.
s['banana':'orange']

banana    20
grapes    30
orange    40
Name: calories, dtype: int64

In [85]:
fruit_protein = {
    "Avocado": 2.0,       # grams of protein
    "Guava": 2.6,
    "Blackberries": 2.0,
    "Oranges": 0.9,
    "Banana": 1.1,
    "Apples": 0.3,
    "Kiwi": 1.1,
    "Pomegranate": 1.7,
    "Mango": 0.8,
    "Cherries": 1.0
}

In [86]:
s2 = pd.Series(fruit_protein, name = "Protein")
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [87]:
# Conditional Selection:

s2[s2>1]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Name: Protein, dtype: float64

In [88]:
# Logical Operators: and, or, not

s2[(s2>0.5) | (s2 <= 2)]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [89]:
# not operation:

s2[~(s2>1)]

Oranges     0.9
Apples      0.3
Mango       0.8
Cherries    1.0
Name: Protein, dtype: float64

In [90]:
# Modyfying the series:

s2["Mango"] = 2.8

In [91]:
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           2.8
Cherries        1.0
Name: Protein, dtype: float64

In [92]:
import numpy as np

In [93]:
ser = pd.Series(['a', np.nan, 1, np.nan, 2])
s.notnull().sum()

np.int64(5)

In [94]:
# DataFrame:

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}

In [95]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [96]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [97]:
df.head(2)

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [98]:
df.tail(3)

    Name   Age Department   Salary
3  David   NaN         IT  62000.0
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [99]:
# loc and iloc

df.iloc[1:3, :2] #rows, columns

      Name   Age
1      Bob  30.0
2  Charlie  35.0

In [100]:
df.loc[1:2, ["Age","Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance

In [101]:
df[["Age", "Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [102]:
df.drop("Age", axis = 1)

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [103]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [104]:
df.shape

(6, 4)

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [106]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [107]:
# Broadcasting

df["Salary"] = df["Salary"] + 5000

In [108]:
df["Salary"]

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [109]:
# Renaming cokumns:

df.rename(columns = {"Department": "Dept"}, inplace = True)

In [110]:
df

      Name   Age     Dept   Salary
0    Alice  25.0       HR  55000.0
1      Bob  30.0       IT  65000.0
2  Charlie  35.0  Finance  75000.0
3    David   NaN       IT  67000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  55000.0

In [111]:
df["Dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [112]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [113]:
df["Promoted Salary"] = df["Salary"] * 10

In [114]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [115]:
# Data Cleaning

df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
Promoted Salary    1
dtype: int64

In [116]:
df.dropna(how = "any") # any row that had any null value

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
5    Alice  25.0       HR  55000.0         550000.0

In [117]:
df.dropna(how = "all") #if all the values in any row are null then we drop that row

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [118]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [119]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [120]:
df["Salary"].fillna(df["Salary"].median())

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    65000.0
5    55000.0
Name: Salary, dtype: float64

In [121]:
df["Age"].fillna(method = "ffill")

/tmp/ipykernel_710/544980945.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "ffill")

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [122]:
df["Age"].fillna(method = "bfill")

/tmp/ipykernel_710/3026805218.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "bfill")

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [123]:
df["Name"] = df["Name"].replace("Charlie", "Rose")

In [124]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0         750000.0
3  David   NaN       IT  67000.0         670000.0
4    Eve  29.0       HR      NaN              NaN
5  Alice  25.0       HR  55000.0         550000.0

In [125]:
# Duplicates:

df_dup = df[df.duplicated(keep = "last")]
df_dup

    Name   Age Dept   Salary  Promoted Salary
0  Alice  25.0   HR  55000.0         550000.0

In [126]:
df = df.drop_duplicates()

In [127]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0         750000.0
3  David   NaN       IT  67000.0         670000.0
4    Eve  29.0       HR      NaN              NaN

In [128]:
# invalid values:
# Lambda -> python

df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x > 650000 else x)

/tmp/ipykernel_710/3688703913.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x > 650000 else x)

In [129]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0          75000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  29.0       HR      NaN              NaN

In [130]:
# apply and lambda
def multiplying_age(x):
  return x*2

df["Age"] = df["Age"].apply(multiplying_age)

/tmp/ipykernel_710/996335713.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(multiplying_age)

In [131]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  50.0       HR  55000.0         550000.0
1    Bob  60.0       IT  65000.0         650000.0
2   Rose  70.0  Finance  75000.0          75000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  58.0       HR      NaN              NaN

In [132]:
df["Age"] = df["Age"].apply(lambda x: x/2)

/tmp/ipykernel_710/1345931692.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(lambda x: x/2)

In [133]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0          75000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  29.0       HR      NaN              NaN

In [134]:
# Joins and Merges

department_info = {
    "Dept": ["HR", "IT", "Finance"],
    "Location": ["New York", "San Francisco", "Chicago"],
    "Manager": ["Laura", "Steve", "Nina"]
}

df2 = pd.DataFrame(department_info)
df2

      Dept       Location Manager
0       HR       New York   Laura
1       IT  San Francisco   Steve
2  Finance        Chicago    Nina

In [135]:
# Concat

pd.concat([df, df2])

    Name   Age     Dept   Salary  Promoted Salary       Location Manager
0  Alice  25.0       HR  55000.0         550000.0            NaN     NaN
1    Bob  30.0       IT  65000.0         650000.0            NaN     NaN
2   Rose  35.0  Finance  75000.0          75000.0            NaN     NaN
3  David   NaN       IT  67000.0          67000.0            NaN     NaN
4    Eve  29.0       HR      NaN              NaN            NaN     NaN
0    NaN   NaN       HR      NaN              NaN       New York   Laura
1    NaN   NaN       IT      NaN              NaN  San Francisco   Steve
2    NaN   NaN  Finance      NaN              NaN        Chicago    Nina

In [136]:
pd.concat([df, df2], axis = 1)

,Name,Age,Dept,Salary,Promoted Salary,Dept,Location,Manager
0,Alice,25.0,HR,55000.0,550000.0,HR,New York,Laura
1,Bob,30.0,IT,65000.0,650000.0,IT,San Francisco,Steve
2,Rose,35.0,Finance,75000.0,75000.0,Finance,Chicago,Nina
3,David,NaN,IT,67000.0,67000.0,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN,NaN

In [137]:
pd.merge(df, df2, on = "Dept")

    Name   Age     Dept   Salary  Promoted Salary       Location Manager
0  Alice  25.0       HR  55000.0         550000.0       New York   Laura
1    Bob  30.0       IT  65000.0         650000.0  San Francisco   Steve
2   Rose  35.0  Finance  75000.0          75000.0        Chicago    Nina
3  David   NaN       IT  67000.0          67000.0  San Francisco   Steve
4    Eve  29.0       HR      NaN              NaN       New York   Laura